/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import EstructurasDeDatos.HashTable;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author fabriziospiotta
 */
public class InterfazInicial extends javax.swing.JFrame {
    
    private static HashTable summaryHashTable;
    private static HashTable autoresHashTable;
    private static HashTable palabrasClaveHashTable;
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazInicial(HashTable summaryHashTable, HashTable autoresHashTable, HashTable palabrasClaveHashTable) {
        this.summaryHashTable = summaryHashTable;
        this.autoresHashTable = autoresHashTable;
        this.palabrasClaveHashTable = palabrasClaveHashTable;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IrMenuButton = new javax.swing.JButton();
        BorrarSistemaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        IrMenuButton.setText("IR AL MENU");
        IrMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IrMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        BorrarSistemaButton.setText("BORRAR SISTEMA PRE-GUARDADO");
        BorrarSistemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarSistemaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BorrarSistemaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IrMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrMenuButtonActionPerformed
        // TODO add your handling code here:
        InterfazMenu menu = new InterfazMenu(summaryHashTable, autoresHashTable, palabrasClaveHashTable);
        this.setVisible(false);
        menu.setVisible(true);                
    }//GEN-LAST:event_IrMenuButtonActionPerformed

    private void BorrarSistemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarSistemaButtonActionPerformed
        // TODO add your handling code here:
        this.summaryHashTable = new HashTable(23);
        try {
            PrintWriter pw = new PrintWriter("test//resumenes_guardados.txt");
            pw.print("");
            pw.close();
            JOptionPane.showMessageDialog(this, "Sistema borrado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al borrar los datos del sistema, porfavor intente de nuevo");
        }
    }//GEN-LAST:event_BorrarSistemaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicial(summaryHashTable, autoresHashTable, palabrasClaveHashTable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarSistemaButton;
    private javax.swing.JButton IrMenuButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
