/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Summary;
import EstructurasDeDatos.HashTable;
import EstructurasDeDatos.Lista;
import EstructurasDeDatos.Nodo;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author fabriziospiotta
 */
public class InterfazMenu extends javax.swing.JFrame {

    static HashTable summaryHashTable;
    static HashTable autoresHashTable;
    static HashTable palabrasClaveHashTable;
    /**
     * Creates new form InterfazMenu
     */
    public InterfazMenu(HashTable summaryHashTable, HashTable autoresHashTable, HashTable palabrasClaveHashTable) {
        this.summaryHashTable = summaryHashTable;
        this.autoresHashTable = autoresHashTable;
        this.palabrasClaveHashTable = palabrasClaveHashTable;
        initComponents();
    }
    public String imprimirResumen(Summary summary) {
        String cadena = "";
        cadena += summary.getTitulo() + "\n" + "\n";
        cadena += "Autores" + "\n";
        Nodo aux = summary.getAutores().getpFirst();
        for (int i = 0; i < summary.getAutores().getSize(); i++) {
           cadena += aux.getElemento() + "\n";
           aux = aux.getpNext();
        }
        cadena += "\n";
        cadena += "Resumen" + "\n";
        cadena += summary.getCuerpoResumen() + "\n" + "\n";
        cadena += "Palabras Claves: ";
        Nodo aux1 = summary.getKeyWords().getpFirst();
        for (int i = 0; i < summary.getKeyWords().getSize()- 1; i++) {
           cadena += aux1.getElemento() + ", ";
           aux1 = aux1.getpNext();
        }
        cadena += summary.getKeyWords().getpLast().getElemento() + ".";
        return cadena;
    }
    
    
    public void escribir_txt() {
        String cadenaDeTexto = "";
        for (int i = 0; i < this.summaryHashTable.getArrayHash().length; i++) {
            if (summaryHashTable.getArrayHash()[i] != null) {
                Lista listaAux = summaryHashTable.getArrayHash()[i];
                Nodo<Summary> aux = listaAux.getpFirst();
                while (aux != null) {
                    cadenaDeTexto += "INVESTIGACION" + "\n";
                    cadenaDeTexto += imprimirResumen(aux.getElemento());
                    cadenaDeTexto += "\n" + "\n" + "\n";
                    aux = aux.getpNext();
                }
            }
        }
        try {
            PrintWriter pw = new PrintWriter("test//resumenes_guardados.txt");
            pw.print(cadenaDeTexto);
            pw.close();
            JOptionPane.showMessageDialog(this, "Registro completado exitosamente!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al importar los datos, porfavor intente de nuevo");
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AgregarResumenButton = new javax.swing.JButton();
        AnalizarResumenButton = new javax.swing.JButton();
        BuscarPalabraClaveButton = new javax.swing.JButton();
        BuscarPorAutorButton = new javax.swing.JButton();
        SalirDelSistemaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        AgregarResumenButton.setText("AGREGAR RESUMEN");
        AgregarResumenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarResumenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarResumenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        AnalizarResumenButton.setText("ANALIZAR RESUMEN");
        AnalizarResumenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalizarResumenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AnalizarResumenButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        BuscarPalabraClaveButton.setText("BUSCAR INVESTIGACIONES POR PALABRA CLAVE");
        BuscarPalabraClaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPalabraClaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarPalabraClaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        BuscarPorAutorButton.setText("BUSCAR INVESTIGACIONES POR AUTOR");
        BuscarPorAutorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPorAutorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarPorAutorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        SalirDelSistemaButton.setText("SALIR DEL SISTEMA");
        SalirDelSistemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirDelSistemaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SalirDelSistemaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarResumenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarResumenButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InterfazAgregarResumen newI = new InterfazAgregarResumen(summaryHashTable, autoresHashTable, palabrasClaveHashTable);
        newI.setVisible(true);
    }//GEN-LAST:event_AgregarResumenButtonActionPerformed

    private void BuscarPalabraClaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPalabraClaveButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InterfazBuscarInvestigacionesPorPalabraClave newI = new InterfazBuscarInvestigacionesPorPalabraClave(summaryHashTable, autoresHashTable, palabrasClaveHashTable);
        newI.setVisible(true);
    }//GEN-LAST:event_BuscarPalabraClaveButtonActionPerformed

    private void BuscarPorAutorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPorAutorButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InterfazBuscarInvestigacionesPorAutor newI = new InterfazBuscarInvestigacionesPorAutor(summaryHashTable, autoresHashTable, palabrasClaveHashTable);
        newI.setVisible(true);
    }//GEN-LAST:event_BuscarPorAutorButtonActionPerformed

    private void AnalizarResumenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalizarResumenButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InterfazAnalizarResumen newI = new InterfazAnalizarResumen(summaryHashTable, autoresHashTable, palabrasClaveHashTable);
        newI.setVisible(true);
    }//GEN-LAST:event_AnalizarResumenButtonActionPerformed

    private void SalirDelSistemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirDelSistemaButtonActionPerformed
        // TODO add your handling code here:
        this.escribir_txt();
    }//GEN-LAST:event_SalirDelSistemaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMenu(summaryHashTable, autoresHashTable, palabrasClaveHashTable).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarResumenButton;
    private javax.swing.JButton AnalizarResumenButton;
    private javax.swing.JButton BuscarPalabraClaveButton;
    private javax.swing.JButton BuscarPorAutorButton;
    private javax.swing.JButton SalirDelSistemaButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
